### PR TITLE
replaced gulp-watch-sequence by runSequence

### LINKED ISSUE #527: scripts ENOENT: no such file or directory
Sometimes I get this no entry error

> [15:42:45] scripts ENOENT: no such file or directory, open '/Users/axawinterthur/dev/style-guide/jquery/datepicker_scsslint_tmp5762205445594462995.js'

Has anyone experienced it too?

### PR DESCRIPTION
**Pull request by AndyOGo**
possibly fixes #527 

Sometimes I get this no entry error

> [15:42:45] scripts ENOENT: no such file or directory, open '/Users/axawinterthur/dev/style-guide/jquery/datepicker_scsslint_tmp5762205445594462995.js'

Or this one

> [10:00:20] plugin.js was changed
> [10:00:21] Starting 'scripts'...
> [10:00:21] Starting 'scripts-transpile'...
> [10:00:21] scripts ENOENT: no such file or directory, lstat '/Users/axawinterthur/dev/style-guide/jquery/plugin_scsslint_tmp2948379016065971722.js'
> events.js:154
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: ENOENT: no such file or directory, open '/Users/axawinterthur/dev/style-guide/jquery/plugin_scsslint_tmp2948379016065971722.js'
>     at Error (native)

Has anyone experienced it too?

The error gets thrown in gulp dev task's watch at:
```js
  watch([
    './jquery/**/*',
  ], (sequence(300)).getHandler('scripts', 'docs-scripts'))
  .on('error', err => errorify(err.message, 'scripts'))
```

### CODE REVIEW

**Comment by AndyOGo** [comment]
seems to be an issue with [gulp-watch-sequence](https://www.npmjs.com/package/gulp-watch-sequence)

Anyway I checked the docs and as I understood it it is a tool meant to prevent executing same task dependencies multiple times if different watcher fires at the same or similar time.
E.g.: your two tasks `js` and `css`, both need to trigger `html` and `reload` tasks after.
In case you have change js and css files and hit "save-all" in your IDE, each of those would trigger `html` and `reload` resulting in 2 calls. Though one would be sufficient.

Therefore the `sequence(300)` returns a queue which can be used in multiple watchers. We don't do this, we just use it in one watcher.

So I think we can replace that code with something like that:
```js
watch([
    './jquery/**/*',
  ], (files, cb) => runSequence(['scripts', 'docs-scripts'], cb))
  .on('error', err => errorify(err.message, 'scripts'))
```

**Comment by AndyOGo** [comment]
Or you want the delay feature, if someone saves multiple times within 300 ms. Don't think that happens that often

**Comment by sventschui** [comment]
Doesn't a save all on two js files trigger two watch events?

**Comment by AndyOGo** [comment]
@sventschui yes that is true too, sorry my example did not clarify this.

**Comment by AndyOGo** [comment]
My problem is after this error happend, no more automatic builds 😞

**Comment by AndyOGo** [comment]
@sventschui 
`gulp-batch` could be an alternative - https://github.com/floatdrop/gulp-batch

**Comment by sventschui** [comment]
Seems to target our issue. Give it a try?

**Comment by AndyOGo** [comment]
@sventschui 
actually the error happens as soon as the scripts-transpile task is run.
The issue should be there then

**Comment by AndyOGo** [comment]
closing this, as it is caused by my IDE

**Pull request closed without merging**
