### PR TITLE
Improvement/add meta language2

### LINKED ISSUE #517: Add meta-language2 from beta.axa.ch to the style guide
Could someone please add the meta-language2 from the beta.axa.ch to the style guide? Thanks!

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #517

### CODE REVIEW

**Comment by elessar-ch** [comment]
Should we update the header example to include the new menu?

**Comment by elessar-ch** [comment]
I switched to a variable for z-index as we did with the others. This allows to have a more complete few of different z-indexes on a glance. Made no changes though.
Additionally added a snippet `header2`. It's the same header just with the new met-language2: http://localhost:3000/components/demos/header2.html

**Comment by AndyOGo** [comment]
I quickly added the react component.
So far there is not demo page running...

**Comment by AndyOGo** [comment]
do you guys wish a complete react-dev setup to be included? babel-preset-react, jsx-support, lints, builds, bla bla bla

**Comment by sventschui** [comment]
I think that would be useful since we want to switch to react components instead of this jquery spaghetti stuff, don't we?

**Pull request merged**
