### PR TITLE
Bring responsive back to our docs!

### PR DESCRIPTION
**Pull request by davidknezic**
Just recently (using my smartphone) I wanted to take a look at some specific recommendations in our Web Style Guide. It was a mess browsing the site in desktop mode. Felt like 10yrs ago. :tired_face: 

That's why I was thinking about how to bring responsiveness back to our style guide docs. Without interferring with our fancy examples resizer, of course.

I thought if we only provide resizing options for the **same or smaller** viewports than your browser is currently in, we should be fine. Nobody wants to see the desktop header on mobile anyway.

ggxrcqgnkn

Cool thing, you have an example in `desktop` viewport and you shrink your browser. The example will automatically switch into `tablet` and then `mobile` viewport. When you stretch your browser back, it will go back to `desktop`. It's because it remembers what viewport you explicitly selected. :star2: 

1cx746kioa

This pr also reduces boilerplate that was necessary to build examples. Thanks to @backflip's groundwork we can do it like this. :muscle:

```jade
+example('/components/demos/loading-spinner.html')
```

Still, there are some things missing:

* [x] change resizing animations to CSS transitions instead jQuery magic
* [x] bring back mobile menu
* [x] hide mobile toggle on mobile altogether
* [ ] add a `.respond()` mixin mode for the widths between mobile and tablet
* [ ] bring @Agatai's brackets back

But I'd first want to hear from you about the idea of bringing responsive back to our docs! @elessar-ch @sventschui

### CODE REVIEW

**Comment by sventschui** [comment]
:+1:  - no more words needed ;)

**Comment by TheDadi** [comment]
Good idea! 👍🏻 

Otherwise we can stick to html9 seems to be a good solution..😋

If you’re feeling overwhelmed by the endless proliferation of responsive grids, adaptive images, HTML boilerplates, CSS frameworks and JavaScript whirligigs then what you need is the HTML9 Responsive Boilerstrap JS.
To install HTML9 Responsive Boilerstrap JS just “attackclone the grit repo pushmerge, then rubygem the lymphnode js shawarma module — and presto!”

If you’re wondering what H9RBS.js actually is, well, you can abandon any hopes of one day being hip. But if you must know, H9RBS.js is a “flexible, dependency-free, lightweight, device-agnostic, modular, baked-in, component framework MVC library shoelacestrap to help you kickstart your responsive CSS-based app architecture backbone kitchensink tweetybirds.”

The hilarity continues on the official HTML9 Responsive Boilerstrap JS website, and there’s a GitHub repo of course. Check out the issues page (“Need unrealistic micro-benchmarks”).
http://html9responsiveboilerstrapjs.com/

**Comment by davidknezic** [comment]
No way!! Where's @TheDadi's awesome comment. Removed?

**Comment by davidknezic** [comment]
Ok, I think this one is ready to merge.

Two points are still missing, but I suggest to resolve them when we have time:

* add a .respond() mixin mode for the widths between mobile and tablet
* bring @Agatai's brackets back

**Comment by davidknezic** [comment]
:tada:

**Pull request merged**
