### PR TITLE
Build all the scripts with browserify 😀

### PR DESCRIPTION
**Pull request by davidknezic**
As a preparation for our community features and all the js that follows, I'm introducing browserify!

It makes our build process much easier. Additionally, I only build one js file for the docs, instead of the three we had before. We surely have some plugins that aren't necessary on the demo pages (like the example resizing), but since these scripts don't influence the other parts it makes sense to reuse one bundle to make things easier.

I decided to shim jQuery, BaconJS, moment and iFrameResizer away, so they don't get included into the bundle. It's on the user of the bundle to make sure that these dependencies are loaded before (preferably from a CDN).

By the way, browserify-shim is working on a cool feature where the shims can be provided from our gulp script instead of our package.json. That's great when shims start to differ between our Web Style Guide and docs build. thlorenz/browserify-shim#195

browserify all the things

### CODE REVIEW

**Comment by davidknezic** [comment]
I'll just have to fix the examples resizing, then it can be merged :wink:

**Comment by davidknezic** [comment]
It's ready!

**Comment by davidknezic** [comment]
@sventschui @elessar-ch It's ready!

**Comment by sventschui** [comment]
Thx

**Pull request merged**
