### PR TITLE
Improve footer component

### PR DESCRIPTION
**Pull request by davidknezic**
Our footer needs a treatment, so it gets easier markup, more modern css and an adjustment to the new design.

* [x] rewrite footer
* [x] only use defined colors
* [x] switch to `em`
* [x] document footer
* [x] add footer to inspiration page

### CODE REVIEW

**Comment by davidknezic** [comment]
Here we go... it's finalized.

screen shot 2015-10-28 at 09 10 01

screen shot 2015-10-28 at 09 11 19

I use this pr to revamp our Style Guide docs footer:

screen shot 2015-10-28 at 09 12 01

Anja additionally provided some more icons @ `24x24`. These are part of this pr, too:

screen shot 2015-10-28 at 09 12 45

**Comment by davidknezic** [comment]
@sventschui @christiancf merge?

**Comment by sventschui** [comment]
I'll have a look

**Comment by sventschui** [comment]
Happy merging! :+1:

**Comment by sventschui** [comment]
Thanks for the awesome refactoring @davidknezic!

**Pull request merged**
