### PR TITLE
Improvement/add user defined functions

### LINKED ISSUE #489: LESS user defined functions
I find it pretty cool to have the ability for user defined functions like `pixelToRem`or other low level or value centric stuff.

I found three possible solutions:

1.  Backticks Hack
see: https://github.com/less/less.js/issues/637#issuecomment-19445138
or: https://github.com/less/less.js/issues/637#issuecomment-168301542
see: http://www.bennadel.com/blog/2638-executing-javascript-in-the-less-css-precompiler.htm
2. NPM plugin (which I don't like that much)
https://www.npmjs.com/package/less-plugin-functions
3. `@plugin` directive

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #489 

## Important

This utilizes the fact that less treats everything inside backticks as JS code and executes it.

The basic idea is as follows:

1. find `less` module
2. get it's exports property to get access to less intrinsic API
3. utilizes `functionRegistry` in `functions` object to add user defined functions

And yes we have access to global variables :)

## Watch out

I got the following error (but don't know why):

> Error: no writecb in Transform class

I had to clean my npm cache, delete all npm modules and run npm install to avoid this error.
```shell
npm cache clean && rm -rf ./node_modules && npm install
```

### CODE REVIEW

**Comment by davidknezic** [comment]
Oh wow, didn't know this is possible! Very interesting approach. Do you think it's stable enough to merge @AndyOGo?

**Comment by AndyOGo** [comment]
@davidknezic 
Hehe, yeah it's nice.
Unfortunately it's not in the documentation anymore, though it still works.
But it was years ago... see cached site: https://web.archive.org/web/20111231053900/http://lesscss.org/#-javascript-evaluation

related links:
http://stackoverflow.com/questions/20091722/evaluate-a-javascript-piece-of-code-inside-a-less-function
https://www.packtpub.com/packtlib/book/Web%20Development/9781782163763/01/ch01lvl1sec17/Using%20JavaScript%20evaluation%20in%20LESS%20(Should%20know)

**Comment by AndyOGo** [comment]
I created an issue for the less docu about backticks:
https://github.com/less/less.js/issues/2923

**Comment by AndyOGo** [comment]
mhm, okay the less team plans to remove the backticks feature with version 3 release.
As Mathew Dean replied it should be marked as deprecated, but I didn't found it anywhere in the current documentation...

**Comment by AndyOGo** [comment]
UPDATE :)
there is this @plugin directive by [Less v2.5.0](https://github.com/less/less.js/blob/master/CHANGELOG.md#250)

**Comment by AndyOGo** [comment]
okidok.
I added a quick sample utilizing the `@plugin` directive syntax.
Unfortunately this also not documented, but i can confirm that it is the [preferred syntax](https://github.com/less/less.js/issues/2923#issuecomment-232323640)

**Comment by AndyOGo** [comment]
@davidknezic @sventschui @elessar-ch 
I will postpone this.
As I would like to know your opinions / needs / usecases for such a feature.

**Comment by AndyOGo** [comment]
I will close this PR because the solutions I offer aren't well document in less-docs though they work.
And i think a PostCSS plugin px-to-rem is cleaner.

**Pull request closed without merging**
