### PR TITLE
Improvement/css combine media queries

### LINKED ISSUE #483: Add CSS mqpacker PostCSS Plugin
We have loads of equal media queries, which could be combined into one.
We gain file size and the browser does not have to parse the same media queries multiple times.

https://github.com/hail2u/node-css-mqpacker

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #483

### CODE REVIEW

**Comment by sventschui** [comment]
We should definitely document this (and also add sth. to the changelog/release notes)

**Comment by AndyOGo** [comment]
@sventschui 
Agree, but where do we such stuff?

**Comment by sventschui** [comment]
Here: https://design.axa.ch/fundamentals/code/getting-started.html

**Comment by sventschui** [comment]
Maybe we should link that page more prominently. /cc @davidknezic

**Comment by AndyOGo** [comment]
@sventschui 
I quickly added a minification hint to the post processing section.
How do we deal with release notes?

**Comment by AndyOGo** [comment]
Okay I have einen Release-Draft erstellt

**Comment by AndyOGo** [comment]
@sventschui 
good to merge now?

**Comment by sventschui** [comment]
Looks good to me :)

**Comment by davidknezic** [comment]
Once more, great work @AndyOGo! Merging now...

**Pull request merged**
