### PR TITLE
Global Page

### PR DESCRIPTION
**Pull request by davidknezic**
Let's introduce a *Going Global* page. :smiley: 

This is still work in progress and I'd love if you @digisz and @elessar-ch could work on it while I'm away on Monday. I found out that the most work that has to be done is figuring out the content, and fixing that nasty Slick plugin.

This branch is automatically deployed to http://style-guide-global.axach.svc.tutum.io/global.html.

The call to action already works :tada:

### CODE REVIEW

**Comment by davidknezic** [comment]
We had a design studio quite a while ago, the one wireframe we took a photo of is still attached to the first pull request #371.

**Comment by digisz** [comment]
input: the rotating element in the header is a bit confusing, since it probably stops rotating when everything is loaded. can you make it rotate forever?

**Comment by davidknezic** [comment]
We could try making it rotate forever and see how that looks. Currently it only rotates 10 degrees starting on page load lasting for a second.

**Comment by davidknezic** [comment]
I tried another animation. Have a look @digisz

**Pull request merged**
