### PR TITLE
slow build

### LINKED ISSUE #569: Slow Build
Thanks to @sventschui to pointing out that the build took 4.23 min and running it again 1.25 min.

This increase is propably also caused by the recent changes I made - nominally adding `jsdoc` provisorily and extending the JS build with `react` plus the generation of 3 bundles (jquery, react and all).

To ease our lives during development we can archive allot with [`gulp-remember`](https://www.npmjs.com/package/gulp-remember) and [`gulp-cached`](https://github.com/contra/gulp-cached)

~~**The other things which are very slow are:**~~
* ~~our call to github's changelog~~
* ~~saving each transpiled JS file to disk, reading them in again and storing a bundle to disk~~
* ~~The same goes for jsdoc, generating a jsdoc file for each js file (only if jsdoc doclets are present)~~

## Edit
Turns out our slowest stuff are `metalsmith` and `browserify` builds, in short `docs` and `scripts`.

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #569 

## To Do

* [ ] ~~add dev mod (e.g. through environment variable)~~
* [x] introduce incremental builds
 * [x] Assets -> see [`gulp-remeber`](https://www.npmjs.com/package/gulp-remember), [`gulp-cached`](https://github.com/contra/gulp-cached)
 * [x] Browserify -> see [Browserify incremental](https://www.npmjs.com/package/browserify-incremental) and [gulp pro](https://github.com/ngryman/gulp-bro)
 * [ ] ~~Less -> see [Incremental LESS Builds with Gulp](http://j2jensen.blogspot.ch/2015/02/incremental-less-builds-with-gulp.html) and [`gulp-progency`](https://www.npmjs.com/package/gulp-progeny)~~ (Less does not support proper caching like SASS)
 * [ ] ~~MetalSmith -> try [`metalsmith-changed`](https://www.npmjs.com/package/metalsmith-changed)~~ (forget it, this plugin is not ready yet for complex caching)
* [x] remove github changelogs

### CODE REVIEW

**Comment by AndyOGo** [comment]
@sventschui @davidknezic @elessar-ch 
Okay, on my machine the build took `43s`. Which is actually worse than before (`35s`), I somehow slowed down the docs.

The slowest things are:
* docs with `31s` - metalsmith does not support incremental builds
* scripts with `11s` - browserify-incremental does not help much
* styles `1.03s` - less does not have caching like sass does...

**Comment by AndyOGo** [comment]
Turns out React is slowing us down massively. They have already a bundled version of react in `dist/react.js`, though their `main` field inside `package.json` says `index.js` which does a whole bunch of requires, which causes browserify to be damn slow...

**Comment by sventschui** [comment]
Have you also timings on the different tasks performed inside `docs`?

**Comment by AndyOGo** [comment]
@sventschui 

> [23:23:57] Starting 'docs'...
> [23:23:57] Starting 'docs-jsdoc-clean'...
> [23:23:57] Finished 'docs-jsdoc-clean' after 2.08 ms
> [23:23:57] Starting 'docs-jsdoc2md'...
> [23:23:58] Finished 'docs-jsdoc2md' after 1.3 s
> [23:23:58] Starting 'docs-pages'...
> [23:23:58] Starting 'docs-scripts'...
> [23:23:58] Starting 'docs-styles'...
> [23:23:58] Starting 'docs-assets'...
> [23:24:19] Finished 'docs-styles' after 21 s
> [23:24:19] Finished 'docs-pages' after 21 s
> [23:24:20] Finished 'docs-scripts' after 22 s
> [23:24:21] Finished 'docs-assets' after 22 s
> [23:24:21] Finished 'docs' after 24 s

**Comment by AndyOGo** [comment]
Build time on my machine is `34s`

```bash
[10:45:48] Starting 'build'...
[10:45:48] Finished 'clean' after 93 ms
[10:45:48] Finished 'images-clean' after 522 μs
[10:45:48] Finished 'images' after 18 ms
[10:45:48] Finished 'icons-copy' after 24 ms
[10:45:49] Finished 'icons' after 233 ms
[10:45:49] Starting 'styles'...
[10:45:49] Finished 'styles-copy' after 53 ms
[10:45:49] Finished 'styles-variables' after 3.44 ms
[10:45:50] Finished 'styles-compile' after 960 ms
[10:45:50] Finished 'styles' after 1.02 s
[10:45:50] Finished 'modernizr' after 355 ms
[10:45:50] Starting 'scripts'...
[10:45:51] Finished 'scripts-transpile' after 1.21 s
[10:46:01] Finished 'scripts-bundle' after 9.92 s
[10:46:01] Finished 'scripts' after 11 s
[10:46:01] Finished 'create-versions-file' after 15 ms
[10:46:01] Starting 'docs'...
[10:46:01] Finished 'docs-jsdoc-clean' after 1.75 ms
[10:46:02] Finished 'docs-jsdoc2md' after 1.3 s
[10:46:20] Finished 'docs-pages' after 18 s
[10:46:20] Finished 'docs-styles' after 18 s
[10:46:22] Finished 'docs-scripts' after 20 s
[10:46:23] Finished 'docs-assets' after 20 s
[10:46:23] Finished 'docs' after 22 s
[10:46:23] Finished 'build' after 34 s
```

**Comment by AndyOGo** [comment]
Though we just made minor speed improvements within this branch I would really like to merge, cause I fixed some bugs and made some clean ups.

Do ya all agree?

**Comment by AndyOGo** [comment]
any feedback, complaints?

**Comment by davidknezic** [comment]
I agree to merge. It's great to speed our build up until we have an even speedier solution in place.

**Pull request merged**
