### PR TITLE
Improvement/mobile language switch

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #591

### CODE REVIEW

**Comment by AndyOGo** [comment]
@davidknezic @sventschui @elessar-ch 
I guess this one can be closed, though I would cherry pick https://github.com/axa-ch/style-guide/pull/595/commits/937225033b458f05a018877b2ea5cbfae9c49854

**Comment by AndyOGo** [comment]
@davidknezic @sventschui @elessar-ch 
We generate the markup for the mobile language switch at the server level now.
So no need for this so far.

I suppose to kick it, but i want to pick https://github.com/axa-ch/style-guide/pull/595/commits/937225033b458f05a018877b2ea5cbfae9c49854

**Comment by davidknezic** [comment]
I think we could use this!

**Comment by sventschui** [comment]
@AndyOGo Agree on picking the div/ul fix, will you do that?

**Comment by AndyOGo** [comment]
@davidknezic @sventschui 
Sure, I can pick that one commit.
Right now I have also no need for a React/jQuery based mobile menu.

**Comment by AndyOGo** [comment]
@davidknezic @sventschui 
Said and done 🍒  with #639

**Pull request closed without merging**
