### PR TITLE
Mobile: Overflow issue in forms

### LINKED ISSUE #598: Android: Overflow issue in forms
Currently we hit more and more issues regarding large content squeezed into a mobile first design approach (see attached images).

Honestly I don't think that it is feasible to restrict content to be only mobile first.
I suppose to make our components bullet proof, with tests/examples for the worst practices included into the docs.
I'm aware that this is a huge burden, but I think would be worth the effort.

One of the main issues is definitely displaying large text on mobile.
I build already two basic solutions to tackle this issue consistently:
* `.ellipsis` mixin - https://design.axa.ch/components/typography.html#long-words-overflow-ellipsis
* `.word-break` mixin - https://design.axa.ch/components/typography.html#long-words-automatic-word-breaking

img_1040
img_1041
img_1042

### PR DESCRIPTION
**Pull request by AndyOGo**
quickly tackles #598 for go live.
This needs to be properly decided and then refactored.

### CODE REVIEW

**Comment by sventschui** [comment]
Same issue presents itself for buttons in myaxa. Could you add ellipsis there too?

**Comment by AndyOGo** [comment]
@sventschui 
A just realized there is a problem with "badged" buttons which are `position: absolute` and would be cut off by ellipsis.
Though I could quickly add an optional `button--ellipsis` modifier.

Does this work for you?

**Comment by AndyOGo** [comment]
@sventschui 
And may I ask you to add a screenshot to the original issue please, so that we don't forget

**Comment by AndyOGo** [comment]
@sventschui 
I just extended the `.ellipsis` and `.word-break` mixins, so that they can be call with `none`. Which will remove it and restores browser defaults.

**Pull request merged**
