### PR TITLE
Update npm deprecated deps

### LINKED ISSUE #604: Update deprecated npm packages
I just run a complete reinstall with:
```sh
rm -r node_modules/ && npm cache clean && npm install && npm install babel-register
```

NPM complaints about:

> npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
> npm WARN deprecated metalsmith-jade@0.0.3: This project has been renamed to metalsmith-pug. please install the latest version of metalsmith-pug instead.
> npm WARN deprecated gulp-foreach@0.1.0: Either use gulp-tap or gulp-flatmap, depending on your needs
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
> npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
> npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
> npm WARN deprecated jade@1.3.1: Jade has been renamed to pug, please install the latest version of pug instead of jade
> npm WARN deprecated lodash.createcallback@2.4.4: This package has been discontinued in favor of lodash.iteratee@^4.0.0.
> npm WARN prefer global jshint@2.9.3 should be installed with -g

`npm ls graceful-fs` prints:

```
├─┬ gulp@3.9.1
│ └─┬ vinyl-fs@0.3.14
│   ├─┬ glob-watcher@0.0.6
│   │ └─┬ gaze@0.5.2
│   │   └─┬ globule@0.1.0
│   │     └─┬ glob@3.1.21
│   │       └── graceful-fs@1.2.3
│   └── graceful-fs@3.0.11
├─┬ gulp-sourcemaps@1.6.0
│ └── graceful-fs@4.1.6
└─┬ gulp-watch@4.3.9
  └─┬ chokidar@1.6.0
    └─┬ fsevents@1.0.14
      └─┬ node-pre-gyp@0.6.29
        └─┬ tar@2.2.1
          └─┬ fstream@1.0.10
            └── graceful-fs@4.1.4
```

`npm ls minimatch` prints:

```
├─┬ del@0.1.3
│ └─┬ globby@0.1.1
│   └─┬ glob@4.5.3
│     └── minimatch@2.0.10
├─┬ gulp@3.9.1
│ └─┬ vinyl-fs@0.3.14
│   ├─┬ glob-stream@3.1.18
│   │ └── minimatch@2.0.10
│   └─┬ glob-watcher@0.0.6
│     └─┬ gaze@0.5.2
│       └─┬ globule@0.1.0
│         └── minimatch@0.2.14
├─┬ gulp-if@1.2.5
│ └─┬ gulp-match@0.2.1
│   └── minimatch@1.0.0
├─┬ gulp-jshint@1.12.0
│ └── minimatch@2.0.10
├─┬ gulp-modernizr@0.0.0
│ └─┬ customizr@1.0.0-alpha
│   └─┬ glob@3.2.11
│     └── minimatch@0.3.0
├─┬ gulp-watch@4.3.9
│ └─┬ chokidar@1.6.0
│   └─┬ fsevents@1.0.14
│     └─┬ node-pre-gyp@0.6.29
│       └─┬ rimraf@2.5.3
│         └─┬ glob@7.0.5
│           └── minimatch@3.0.2
├─┬ metalsmith@1.7.0
│ └─┬ recursive-readdir@1.3.0
│   └── minimatch@0.3.0
├─┬ metalsmith-branch@0.0.4
│ └─┬ multimatch@0.1.0
│   └── minimatch@0.2.14
├─┬ metalsmith-collections@0.7.0 (git+https://github.com/axa-ch/metalsmith-collections.git#72da72a5745ba952f93920872a9fbbb42d3284e0)
│ └── minimatch@0.2.14
├─┬ metalsmith-copy@0.2.1
│ └── minimatch@0.2.14
├─┬ metalsmith-ignore@0.1.2
│ └─┬ multimatch@0.1.0
│   └── minimatch@0.2.14
├─┬ metalsmith-templates@0.6.0 (git+https://github.com/axa-ch/metalsmith-templates.git#0e5d64659d5811150fa7a4645f37f080b6e7d21a)
│ └─┬ multimatch@0.1.0
│   └── minimatch@0.2.14
└── minimatch@3.0.3
```

`npm ls win-spawn` prints:

```
└─┬ gulp-modernizr@0.0.0
  └─┬ customizr@1.0.0-alpha
    └── win-spawn@2.0.0
```

`npm ls transformers` prints:

```
└─┬ jade@1.11.0
  └── transformers@2.1.0
```

`npm ls lodash` prints:

```
├─┬ babel-core@6.14.0
│ ├─┬ babel-generator@6.14.0
│ │ └── lodash@4.16.1
│ ├─┬ babel-template@6.15.0
│ │ └── lodash@4.16.1
│ ├─┬ babel-traverse@6.15.0
│ │ └── lodash@4.16.1
│ ├─┬ babel-types@6.15.0
│ │ └── lodash@4.16.1
│ └── lodash@4.16.1
├─┬ babel-preset-es2015@6.14.0
│ ├─┬ babel-plugin-transform-es2015-block-scoping@6.15.0
│ │ └── lodash@4.16.1
│ ├─┬ babel-plugin-transform-es2015-classes@6.14.0
│ │ └─┬ babel-helper-define-map@6.9.0
│ │   └── lodash@4.16.1
│ └─┬ babel-plugin-transform-es2015-sticky-regex@6.8.0
│   └─┬ babel-helper-regex@6.9.0
│     └── lodash@4.16.1
├─┬ babel-preset-react@6.11.1
│ └─┬ babel-plugin-transform-react-jsx@6.8.0
│   └─┬ babel-helper-builder-react-jsx@6.9.0
│     └── lodash@4.16.1
├─┬ babel-register@6.14.0
│ └── lodash@4.16.1
├─┬ eslint@3.5.0
│ ├─┬ inquirer@0.12.0
│ │ └── lodash@4.16.1
│ ├── lodash@4.16.1
│ └─┬ table@3.8.0
│   └── lodash@4.16.1
├─┬ gulp@3.9.1
│ └─┬ vinyl-fs@0.3.14
│   └─┬ glob-watcher@0.0.6
│     └─┬ gaze@0.5.2
│       └─┬ globule@0.1.0
│         └── lodash@1.0.2
├─┬ gulp-jshint@1.12.0
│ ├─┬ jshint@2.9.3
│ │ └── lodash@3.7.0
│ └─┬ rcloader@0.1.2
│   └── lodash@2.4.2
├─┬ gulp-less@3.1.0
│ └─┬ accord@0.23.0
│   └── lodash@4.11.2
├─┬ gulp-modernizr@0.0.0
│ ├─┬ customizr@1.0.0-alpha
│ │ └─┬ modernizr@3.3.1
│ │   └── lodash@4.0.0
│ └─┬ grunt-legacy-log@0.1.3
│   ├─┬ grunt-legacy-log-utils@0.1.1
│   │ └── lodash@2.4.2
│   └── lodash@2.4.2
├─┬ gulp-tar@1.9.0
│ └─┬ archiver@1.1.0
│   ├─┬ archiver-utils@1.3.0
│   │ └── lodash@4.16.1
│   ├── lodash@4.16.1
│   └─┬ zip-stream@1.1.0
│     └── lodash@4.16.1
├─┬ gulp-template@1.1.1
│ └── lodash@2.4.2
├─┬ jsdoc-babel@0.2.1
│ └── lodash@4.16.1
├── lodash@3.10.1
├─┬ metalsmith-branch@0.0.4
│ └─┬ multimatch@0.1.0
│   └── lodash@2.4.2
├─┬ metalsmith-copy@0.2.1
│ └── lodash@2.4.2
├─┬ metalsmith-ignore@0.1.2
│ └─┬ multimatch@0.1.0
│   └── lodash@2.4.2
└─┬ metalsmith-templates@0.6.0 (git+https://github.com/axa-ch/metalsmith-templates.git#0e5d64659d5811150fa7a4645f37f080b6e7d21a)
  └─┬ multimatch@0.1.0
    └── lodash@2.4.2
```

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #604 

Todo:
- [x] Replace `jade` with `pug`
 - [x] Replace `metalsmith-jade` with `metalsmith-pug`
 - [x] Rewrite `.jade` file extension to `.pug`
- [x] replace deprecated `https://github.com/segmentio/metalsmith-templates` with suggested ones here: https://github.com/segmentio/metalsmith-templates
- [x] remove `jshint-stylish` devDependency (since we use ESLint)
- [x] remove `gulp-jshint`
- [ ] remove deprecated `gulp-foreach` - Either use gulp-tap or gulp-flatmap, depending on your needs

**Note** Gulp stuff could skipped, since we are refactoring the whole build w/o gulp

migration guide from jade to pug:
https://pugjs.org/api/migration-v2.html
https://pugjs.org/language/attributes.html#attribute-interpolation

### CODE REVIEW

**Comment by AndyOGo** [comment]
`metalsmith-layouts` throughs `SyntaxError: Assigning to rvalue (5:0)` from within [acorn.js](https://github.com/ternjs/acorn/issues/473)

**Comment by elessar-ch** [comment]
@AndyOGo When do you get that error with metalsmith-layouts?

**Comment by AndyOGo** [comment]
@elessar-ch I got it if I run the build using jade as the template engine.
I had no time so far to figure it out, but it seems to be a jade version issue???

**Comment by AndyOGo** [comment]
will merge as the gulp stuff is obsolete and the pug stuff was done by @elessar-ch

**Pull request merged**
