### PR TITLE
Happypack plus extract text plugin

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes Happypack part of #614 regarding extract-text-webpack-plugin plus postcss

Thanks to https://github.com/amireh/happypack/issues/14#issuecomment-249904627

### CODE REVIEW

**Comment by elessar-ch** [comment]
@AndyOGo there's still an issue when doing the prod build. Maybe you see the problem right away?

**Comment by AndyOGo** [comment]
@elessar-ch 
I guess the issue is regarding this https://github.com/amireh/happypack/issues/14#issuecomment-250719700

**Comment by elessar-ch** [comment]
The error appears when doing `npm run build` and in the docker build:
```
Error: Cannot resolve module 'scss' in C:\dev\repos\axa-ch\style-guide
    at innerCallback (C:\dev\repos\axa-ch\style-guide\node_modules\enhanced-resolve\lib\Resolver.js:91:16)
    at loggingCallbackWrapper (C:\dev\repos\axa-ch\style-guide\node_modules\enhanced-resolve\lib\createInnerCallback.js:21:19)
    at C:\dev\repos\axa-ch\style-guide\node_modules\tapable\lib\Tapable.js:134:6
    at C:\dev\repos\axa-ch\style-guide\node_modules\enhanced-resolve\lib\ModulesInDirectoriesPlugin.js:54:23
    at C:\dev\repos\axa-ch\style-guide\node_modules\enhanced-resolve\lib\Resolver.js:191:15
    at C:\dev\repos\axa-ch\style-guide\node_modules\enhanced-resolve\lib\ModulesInDirectoriesPlugin.js:45:26
    at loggingCallbackWrapper (C:\dev\repos\axa-ch\style-guide\node_modules\enhanced-resolve\lib\createInnerCallback.js:21:19)
    at C:\dev\repos\axa-ch\style-guide\node_modules\tapable\lib\Tapable.js:134:6
    at C:\dev\repos\axa-ch\style-guide\node_modules\enhanced-resolve\lib\Resolver.js:191:15
    at C:\dev\repos\axa-ch\style-guide\node_modules\enhanced-resolve\lib\ModuleTemplatesPlugin.js:40:24
    at loggingCallbackWrapper (C:\dev\repos\axa-ch\style-guide\node_modules\enhanced-resolve\lib\createInnerCallback.js:21:19)
    at C:\dev\repos\axa-ch\style-guide\node_modules\tapable\lib\Tapable.js:134:6
    at C:\dev\repos\axa-ch\style-guide\node_modules\enhanced-resolve\lib\Resolver.js:122:33
    at C:\dev\repos\axa-ch\style-guide\node_modules\enhanced-resolve\lib\Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (C:\dev\repos\axa-ch\style-guide\node_modules\enhanced-resolve\lib\Resolver.js:110:4)
    at loggingCallbackWrapper (C:\dev\repos\axa-ch\style-guide\node_modules\enhanced-resolve\lib\createInnerCallback.js:21:19)
    at C:\dev\repos\axa-ch\style-guide\node_modules\tapable\lib\Tapable.js:134:6
    at Tapable.<anonymous> (C:\dev\repos\axa-ch\style-guide\node_modules\enhanced-resolve\lib\FileAppendPlugin.js:31:26)
    at C:\dev\repos\axa-ch\style-guide\node_modules\enhanced-resolve\lib\Resolver.js:191:15
    at C:\dev\repos\axa-ch\style-guide\node_modules\enhanced-resolve\lib\FileAppendPlugin.js:28:12
    at Storage.finished (C:\dev\repos\axa-ch\style-guide\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at C:\dev\repos\axa-ch\style-guide\node_modules\graceful-fs\polyfills.js:264:29
    at FSReqWrap.oncomplete (fs.js:117:15)
resolve module scss in C:\dev\repos\axa-ch\style-guide
  looking for modules in C:\dev\repos\axa-ch\style-guide\node_modules
    module variation scss-webpack-loader
      C:\dev\repos\axa-ch\style-guide\node_modules\scss-webpack-loader doesn't exist (module as directory)
      resolve 'file' scss-webpack-loader in C:\dev\repos\axa-ch\style-guide\node_modules
        resolve file
          C:\dev\repos\axa-ch\style-guide\node_modules\scss-webpack-loader doesn't exist
          C:\dev\repos\axa-ch\style-guide\node_modules\scss-webpack-loader.webpack-loader.js doesn't exist
          C:\dev\repos\axa-ch\style-guide\node_modules\scss-webpack-loader.web-loader.js doesn't exist
          C:\dev\repos\axa-ch\style-guide\node_modules\scss-webpack-loader.loader.js doesn't exist
          C:\dev\repos\axa-ch\style-guide\node_modules\scss-webpack-loader.js doesn't exist
    module variation scss-web-loader
      C:\dev\repos\axa-ch\style-guide\node_modules\scss-web-loader doesn't exist (module as directory)
      resolve 'file' scss-web-loader in C:\dev\repos\axa-ch\style-guide\node_modules
        resolve file
          C:\dev\repos\axa-ch\style-guide\node_modules\scss-web-loader doesn't exist
          C:\dev\repos\axa-ch\style-guide\node_modules\scss-web-loader.web-loader.js doesn't exist
          C:\dev\repos\axa-ch\style-guide\node_modules\scss-web-loader.webpack-loader.js doesn't exist
          C:\dev\repos\axa-ch\style-guide\node_modules\scss-web-loader.loader.js doesn't exist
          C:\dev\repos\axa-ch\style-guide\node_modules\scss-web-loader.js doesn't exist
    module variation scss-loader
      C:\dev\repos\axa-ch\style-guide\node_modules\scss-loader doesn't exist (module as directory)
      resolve 'file' scss-loader in C:\dev\repos\axa-ch\style-guide\node_modules
        resolve file
          C:\dev\repos\axa-ch\style-guide\node_modules\scss-loader doesn't exist
          C:\dev\repos\axa-ch\style-guide\node_modules\scss-loader.web-loader.js doesn't exist
          C:\dev\repos\axa-ch\style-guide\node_modules\scss-loader.webpack-loader.js doesn't exist
          C:\dev\repos\axa-ch\style-guide\node_modules\scss-loader.loader.js doesn't exist
          C:\dev\repos\axa-ch\style-guide\node_modules\scss-loader.js doesn't exist
    module variation scss
      C:\dev\repos\axa-ch\style-guide\node_modules\scss doesn't exist (module as directory)
      resolve 'file' scss in C:\dev\repos\axa-ch\style-guide\node_modules
        resolve file
          C:\dev\repos\axa-ch\style-guide\node_modules\scss doesn't exist
          C:\dev\repos\axa-ch\style-guide\node_modules\scss.web-loader.js doesn't exist
          C:\dev\repos\axa-ch\style-guide\node_modules\scss.webpack-loader.js doesn't exist
          C:\dev\repos\axa-ch\style-guide\node_modules\scss.loader.js doesn't exist
          C:\dev\repos\axa-ch\style-guide\node_modules\scss.js doesn't exist
```

**Comment by AndyOGo** [comment]
weird

**Comment by elessar-ch** [comment]
`npm run dev` works

**Comment by AndyOGo** [comment]
Yep I know, because does not need the webpack text extract plugin

**Comment by AndyOGo** [comment]
Okay I looked into it, the config is wrong.

**Comment by AndyOGo** [comment]
now i get:

````sh
ERROR in ./docs/scss/docs.scss
Module build failed: ModuleParseError: Module parse failed: /Users/axawinterthur/dev/style-guide/docs/scss/highlight.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExpression (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:1573:21)
    at Parser.pp$1.parseStatement (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:727:47)
    at Parser.pp$1.parseTopLevel (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/axawinterthur/dev/style-guide/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/axawinterthur/dev/style-guide/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/axawinterthur/dev/style-guide/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/axawinterthur/dev/style-guide/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/axawinterthur/dev/style-guide/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/axawinterthur/dev/style-guide/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/axawinterthur/dev/style-guide/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
    at DependenciesBlock.<anonymous> (/Users/axawinterthur/dev/style-guide/node_modules/webpack/lib/NormalModule.js:113:20)
    at DependenciesBlock.onModuleBuild (/Users/axawinterthur/dev/style-guide/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/axawinterthur/dev/style-guide/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/axawinterthur/dev/style-guide/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/axawinterthur/dev/style-guide/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/axawinterthur/dev/style-guide/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
 @ ./docs/js/index-with-styles.js 3:0-28
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
       [2] ./docs/scss/highlight.css 0 bytes [built] [failed]
           cjs require -!!!!./highlight.css [0] ./~/happypack/loader.js?id=production-sass!./docs/scss/docs.scss 3:10-41
        + 2 hidden modules

    ERROR in ./docs/scss/highlight.css
    Module parse failed: /Users/axawinterthur/dev/style-guide/docs/scss/highlight.css Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected token (1:0)
        at Parser.pp$4.raise (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
        at Parser.pp.unexpected (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
        at Parser.pp$3.parseExprAtom (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
        at Parser.pp$3.parseExprSubscripts (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
        at Parser.pp$3.parseMaybeUnary (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
        at Parser.pp$3.parseExprOps (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
        at Parser.pp$3.parseMaybeConditional (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
        at Parser.pp$3.parseMaybeAssign (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
        at Parser.pp$3.parseExpression (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:1573:21)
        at Parser.pp$1.parseStatement (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:727:47)
        at Parser.pp$1.parseTopLevel (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
        at Parser.parse (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
        at Object.parse (/Users/axawinterthur/dev/style-guide/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
        at Parser.parse (/Users/axawinterthur/dev/style-guide/node_modules/webpack/lib/Parser.js:902:15)
        at DependenciesBlock.<anonymous> (/Users/axawinterthur/dev/style-guide/node_modules/webpack/lib/NormalModule.js:104:16)
        at DependenciesBlock.onModuleBuild (/Users/axawinterthur/dev/style-guide/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
        at nextLoader (/Users/axawinterthur/dev/style-guide/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
        at /Users/axawinterthur/dev/style-guide/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
        at Storage.finished (/Users/axawinterthur/dev/style-guide/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
        at /Users/axawinterthur/dev/style-guide/node_modules/graceful-fs/graceful-fs.js:78:16
        at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
     @ ./~/happypack/loader.js?id=production-sass!./docs/scss/docs.scss 3:10-41
````

**Comment by AndyOGo** [comment]
https://github.com/jtangelder/sass-loader/issues/101

**Comment by sventschui** [comment]
> @jsg2021 When you add the .css extension, libsass does not include the file, it just turns it into @import url(..). When this is passed to the css-loader, all urls must be relative to the file which imports them. When you omit .css, libsass includes the file just like it was a .scss file. In this situation, all urls must be relative to the entry sass/scss file which was passed to the sass compiler.
>
> This is how libsass handles it, the sass-loader is just imitating it.

Think the issue is the `.css` in the import

**Comment by AndyOGo** [comment]
@sventschui 
I think so too. And that is the actual bug.
Because we have once `style.scss` as the root file and once `docs.scss` and we can not supply the path for each of them, just for one.
That is one reason I did not like webpack to handle other stuff than JS, because webpack's loaders are changing how node-sass, less etc are resolving dependencies/@imports...

**Comment by sventschui** [comment]
Ok for me

**Comment by AndyOGo** [comment]
@elessar-ch @sventschui @davidknezic 
Okidok, I renamed it for now.
I hope we find a cleaner solution in the future.

**Comment by AndyOGo** [comment]
any feedback on this?

**Comment by sventschui** [comment]
Works for me :)

**Pull request merged**
