### PR TITLE
Improvement/switch to faster uglification

### LINKED ISSUE #671: switch to webpack-parallel-uglify-plugin
I don't know why, but turned out that [`webpack-uglify-parallel`](https://www.npmjs.com/package/webpack-uglify-parallel) is much slower than [`webpack-parallel-uglify-plugin`](https://www.npmjs.com/package/webpack-parallel-uglify-plugin)

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #671 

~~Perf notes:~~

**Don't mind, these test are based on wrong circumstances**

# webpack-uglify-parallel

~~`17315ms` 👎 ~~
~~real	`0m44.898s`~~
~~user	`1m2.023s`~~
~~sys	`0m4.927s`~~

# webpack-parallel-uglify-plugin

**fresh**
~~`9586ms` 👍 ~~
~~real	`0m38.274s`~~
~~user	`0m57.723s`~~
~~sys	`0m3.041s`~~

**cached**
~~`9002ms` 👍 👍 ~~
~~real	`0m36.207s`~~
~~user	`0m56.936s`~~
~~sys	`0m2.921s`~~

### CODE REVIEW

**Comment by AndyOGo** [comment]
Well, I guess "Zu früh gefreut".
It seems it [omids sourcemaps](https://github.com/gdborton/webpack-parallel-uglify-plugin/issues), even if they are configured...

**Comment by AndyOGo** [comment]
Closing this, as it does not support sourcemaps...

**Comment by davidknezic** [comment]
A shame 😢

**Comment by AndyOGo** [comment]
I know 😭

**Pull request closed without merging**
