### PR TITLE
Feature/checkbox variations

### PR DESCRIPTION
**Pull request by FrediBach**
Contains the new checkbox variations and the new progress bar (AEM-1369 & AEM-1374).

### CODE REVIEW

**Comment by davidknezic** [comment]
@FrediBach is it possible that every single commit in this pr is also part of #455?

**Comment by davidknezic** [comment]
checkbox-button-group-bug

There's a problem with the *checkbox group as buttons*. Everything else is fine. Can you look into that @FrediBach?

**Comment by FrediBach** [comment]
Bug is fixed.

> is it possible that every single commit in this pr is also part of #455?

I accidentally copied the #455 feature branch when starting with this feature and not develop.

**Comment by davidknezic** [comment]
Awesome, great work @FrediBach!

**Pull request merged**
