### PR TITLE
Flex the Header

### PR DESCRIPTION
**Pull request by davidknezic**
Makes the Header flex!

This is how our header works now:

```jade
header.header
  .header__meta
    .header__meta__container
      .header__meta__row
        ul.header__meta__item.header__meta__menu.meta-menu
          // ...
        .header__meta__item.header__meta__search.search.search--header
          // ...
        .header__meta__item.header__meta__language
          // ...
        a.header__meta__item.header__meta__action myAXA Login
  .header__main
    .header__main__container
      .header__main__row
        a.header__main__item.header__main__brand.brand(href="#")
          // ...
        ul.header__main__item.header__main__menu.menu-main
          // ...
        a.header__main__item.header__main__mobile-action(href="#")
          // ...
        a.header__main__item.header__main__mobile-action.site__burger(data-burger, href="#")
          // ...
```

Some change highlights:

* Make the header fully flex
* Move `menu--meta` to its own `meta-menu` block
* Fixe padding of the brand block
* Show thick blue header line on mobile too

### CODE REVIEW

**Comment by sventschui** [comment]
We should BEM all the things (e.g. `.header__main__item.header__main__brand` => `.header__main__item.header__main__item--brand`)

**Comment by davidknezic** [comment]
Good suggestion @sventschui. Changed it.

Will just have to figure out how to handle this sort of stuff:

```jade
a.header__main__item.header__main__item--mobile-action.site__burger(data-burger, href="#")
  svg.header__main__mobile-icon.icon.burger-icon(data-burger)
```

`.header__main__mobile-icon` is actually an element of the non existant `mobile-action` block.

And a similar case:

```jade
.header__meta__item.header__meta__item--language
  a.header__meta__language-button(href="#", data-popover="#languageMenu")
```

Where `.header__meta__language-button` is an element of the non existant `language` block, too.

**Comment by sventschui** [comment]
image

`.header__main__mobile-icon` can be dropped. Currently it's including a `display: block` only that doesn't have any effect at all. When removing is not an option I'd think about moving it to `site__burger__icon`, depending on what's the purpose of the styles applied using this selector.

For the `.header__meta__language-button` I'd recommend to introduce the `language` block and the `language__button` element. What do you think?

**Comment by davidknezic** [comment]
Haha.. I love that meme! But it's not that bad, is it? :laughing: 

Will take a look at those two cases tomorrow, I also think it will be a new block for the latter case, don't know yet for the first one, but will surely figure something out.

**Comment by davidknezic** [comment]
Removed the `header__main__mobile-icon` altogether, because it really wasn't necessary anymore.

Introduced the `meta-language` block, that could potentially be extended in the future, so it contains some popover overrides.

**Comment by elessar-ch** [comment]
Looks good now.

**Pull request merged**
