### PR TITLE
updated typography names

### LINKED ISSUE #477: Typography hasn't proper names
At the moment our general typography examples don't have semantic names, just `Lorem Ipsum dolor`.

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #477 
I sat down with design and incorporated semantic names.

### CODE REVIEW

**Comment by sventschui** [comment]
Running text seriously 19/16px? Shouldn't running text be 16/14px?

**Comment by AndyOGo** [comment]
Nope, that is Text Large.

**Comment by sventschui** [comment]
```
+.page-content.page-content--fit
 +  p.make-font-large Running Text
 +  p.paragraph Preset: large
 +  p.paragraph Desktop: 17px=1.0625rem, font-face: book (weight: normal), line-height: 1.8
 +  p.paragraph Mobile: 16px=1rem, font-face: book (weight: normal), line-height: 1.8
 +  p.paragraph Attention: Design uses a 19px font and 1.6 line-height. But the 19px font is rendered pretty weird in all browsers on Windows so we use 17px font and line-height 1.8.
 +  p.paragraph E.g. running text
```

So Running Text is 19/16?!

**Comment by AndyOGo** [comment]
As it says, in design yes. But Windows does really weird things in all browsers with a 19px font, hence we use 17px.

**Comment by sventschui** [comment]
LGTM

**Pull request merged**
