### PR TITLE
Fix IE flexbox problem

### PR DESCRIPTION
**Pull request by elessar-ch**
Fix a problem, where IE 11 doesn't correctly include margin and padding when calculating the with of flexbox children.
Used the workaround described here: [Flexbugs](https://github.com/philipwalton/flexbugs#7-flex-basis-doesnt-account-for-box-sizingborder-box)

### CODE REVIEW

**Comment by davidknezic** [comment]
Nice! Is it ready to merge? You can signal this adding the `needs review` label.

**Comment by sventschui** [comment]
Shouldn't we fix this bug with a postcss plugin? I think this is not the last time we will face this issue. We could even contribute to https://github.com/luisrudge/postcss-flexbugs-fixes

By the way this fix may even collide with the -ms-flex thingys introduces by autoprefixer. Have you checked on that?

**Comment by elessar-ch** [comment]
@sventschui I'm not sure how often we'll come across this issue in the future. Might also be a problem when the class already specifies a width.

Autoprefixer does not override an already specified prefix.

**Comment by davidknezic** [comment]
Will merge, feel free to extend a `postcss` plugin and add it.

**Pull request merged**
