### PR TITLE
Rework typography

### PR DESCRIPTION
**Pull request by elessar-ch**
I created mixins for the typography as designed by @anja225.

I'm not really happy with the naming of the mixins. Any input will be appreciated.

- make-font-heading-primary
- make-font-heading-secondary
- make-font-heading-tertiary
- make-font-x-large
- make-font-large
- make-font-large-semibold
- make-font-medium
- make-font-medium-semibold
- make-font-small-semibold

Furthermore I'm not sure whether we need the heading block defined in the style guide. I personally think everybody should use the mixins and we do the same and define headings in the docs.

@davidknezic @sventschui What do you think?

### CODE REVIEW

**Comment by elessar-ch** [comment]
Todo:

- [ ] docs

**Comment by sventschui** [comment]
I'd still stick to the classes since we use them heavily for rapid prototyping or in some screens of our application. Furthermore I'd

**Comment by elessar-ch** [comment]
Our heading and paragraph classes also define margins, paddings and colors, whereas the mixins define purely font-size, font-weight and line-height to be more flexible.

For this reason I think it's better to stick with mixins even if we keep the heading and paragraph classes.

**Comment by davidknezic** [comment]
Agree with @sventschui, we should keep the `heading` classes. It's probably one of the first components someone uses from the style guide.

I currently don't have a better idea on the naming of the mixins, that's why I'd leave them as they are. If there's a better way, we'll find out sooner or later.

Will merge this, even though the docs aren't final, so I can use the mixins for the footer.

**Pull request merged**
